export const PRICE_RANGE_LABELS: Record<string, string> = {
    low: 'Economico',
    medium: 'Medio',
    high: 'Alto',
    premium: 'Premium',
};

export const PAYMENT_METHOD_OPTIONS = [
    'Efectivo',
    'Tarjeta',
    'Contactless',
    'Bizum',
    'Apple Pay',
    'Google Pay',
    'PayPal',
    'Transferencia',
    'Cheque gourmet',
    'Ticket Restaurant',
    'Sodexo',
    'American Express',
    'Visa',
    'Mastercard',
    'Pago online',
    'Pago en app',
    'Contra reembolso',
];

export const BUSINESS_SERVICE_OPTIONS = [
    'Comer en local',
    'Terraza',
    'Reservas',
    'Para llevar',
    'Entrega a domicilio',
    'Recogida en local',
    'Pedidos online',
    'Menu del dia',
    'Menu infantil',
    'Opciones vegetarianas',
    'Opciones veganas',
    'Sin gluten',
    'Sin lactosa',
    'Desayunos',
    'Brunch',
    'Comidas',
    'Cenas',
    'Copas',
    'Cafe',
    'Cocteles',
    'Vino',
    'Cerveza',
    'Música en directo',
    'Eventos privados',
    'Catering',
    'Cumpleanos',
    'Apto para grupos',
    'Apto para familias',
    'Pet friendly',
    'WiFi',
    'Enchufes',
    'Aire acondicionado',
    'Calefaccion',
    'Television',
    'Parking',
    'Parking cercano',
    'Aparcacoches',
    'Acceso sin escalon',
    'Bano adaptado',
    'Tronas',
    'Cambiador para bebes',
    'Pago en mesa',
    'Zona fumadores',
    'Zona tranquila',
    'Vistas',
    'Azotea',
];

export const ALLERGEN_OPTIONS = [
    'Gluten',
    'Lactosa',
    'Frutos secos',
    'Cacahuetes',
    'Huevo',
    'Soja',
    'Pescado',
    'Crustaceos',
    'Moluscos',
    'Apio',
    'Mostaza',
    'Sesamo',
    'Sulfitos',
    'Altramuces',
];

export const CROSS_CONTAMINATION_LABELS: Record<string, string> = {
    unknown: 'No indicado',
    possible: 'Puede haber contaminacion cruzada',
    controlled: 'Protocolo para reducir contaminacion cruzada',
    dedicated: 'Zona o preparacion separada sin gluten',
};
