const PLACE_TYPE_LABELS: Record<string, string> = {
    // Food and drink
    acai_shop: 'Açai',
    afghani_restaurant: 'Restaurante afgano',
    african_restaurant: 'Restaurante africano',
    american_restaurant: 'Restaurante americano',
    argentinian_restaurant: 'Restaurante argentino',
    asian_fusion_restaurant: 'Fusión asiática',
    asian_restaurant: 'Restaurante asiático',
    australian_restaurant: 'Restaurante australiano',
    austrian_restaurant: 'Restaurante austriaco',
    bagel_shop: 'Bagels',
    bakery: 'Panadería',
    bangladeshi_restaurant: 'Restaurante bangladesí',
    bar: 'Bar',
    bar_and_grill: 'Bar y parrilla',
    barbecue_restaurant: 'Barbacoa',
    basque_restaurant: 'Restaurante vasco',
    bavarian_restaurant: 'Restaurante bávaro',
    beer_garden: 'Cervecería al aire libre',
    belgian_restaurant: 'Restaurante belga',
    bistro: 'Bistró',
    brazilian_restaurant: 'Restaurante brasileño',
    breakfast_restaurant: 'Desayunos',
    brewery: 'Fábrica de cerveza',
    brewpub: 'Brewpub',
    british_restaurant: 'Restaurante británico',
    brunch_restaurant: 'Brunch',
    buffet_restaurant: 'Buffet',
    burmese_restaurant: 'Restaurante birmano',
    burrito_restaurant: 'Burritos',
    cafe: 'Café',
    cafeteria: 'Cafetería',
    cajun_restaurant: 'Restaurante cajún',
    cake_shop: 'Pastelería',
    cambodian_restaurant: 'Restaurante camboyano',
    candy_store: 'Tienda de dulces',
    cantonese_restaurant: 'Restaurante cantonés',
    caribbean_restaurant: 'Restaurante caribeño',
    cat_cafe: 'Café con gatos',
    chicken_restaurant: 'Pollo',
    chinese_restaurant: 'Restaurante chino',
    chocolate_factory: 'Fábrica de chocolate',
    chocolate_shop: 'Chocolatería',
    coffee_shop: 'Cafetería',
    confectionery: 'Confitería',
    deli: 'Delicatessen',
    dessert_restaurant: 'Postres',
    dessert_shop: 'Tienda de postres',
    diner: 'Diner',
    dog_cafe: 'Café con perros',
    donut_shop: 'Donuts',
    fast_food_restaurant: 'Comida rápida',
    fine_dining_restaurant: 'Alta cocina',
    food: 'Comida',
    food_court: 'Zona de restauración',
    french_restaurant: 'Restaurante francés',
    greek_restaurant: 'Restaurante griego',
    hamburger_restaurant: 'Hamburguesería',
    ice_cream_shop: 'Heladería',
    indian_restaurant: 'Restaurante indio',
    indonesian_restaurant: 'Restaurante indonesio',
    italian_restaurant: 'Restaurante italiano',
    japanese_restaurant: 'Restaurante japonés',
    juice_shop: 'Zumos',
    korean_restaurant: 'Restaurante coreano',
    lebanese_restaurant: 'Restaurante libanés',
    meal_delivery: 'Entrega de comida',
    meal_takeaway: 'Para llevar',
    mediterranean_restaurant: 'Restaurante mediterráneo',
    mexican_restaurant: 'Restaurante mexicano',
    middle_eastern_restaurant: 'Restaurante de Oriente Medio',
    pizza_restaurant: 'Pizzería',
    ramen_restaurant: 'Ramen',
    restaurant: 'Restaurante',
    sandwich_shop: 'Bocadillos',
    seafood_restaurant: 'Marisquería',
    spanish_restaurant: 'Restaurante español',
    steak_house: 'Asador',
    sushi_restaurant: 'Sushi',
    thai_restaurant: 'Restaurante tailandés',
    turkish_restaurant: 'Restaurante turco',
    vegan_restaurant: 'Restaurante vegano',
    vegetarian_restaurant: 'Restaurante vegetariano',
    vietnamese_restaurant: 'Restaurante vietnamita',
    wine_bar: 'Vinoteca',

    // Culture and leisure
    art_gallery: 'Galería de arte',
    art_museum: 'Museo de arte',
    art_studio: 'Estudio de arte',
    auditorium: 'Auditorio',
    castle: 'Castillo',
    cultural_landmark: 'Lugar cultural',
    fountain: 'Fuente',
    historical_landmark: 'Monumento histórico',
    historical_place: 'Lugar histórico',
    history_museum: 'Museo de historia',
    monument: 'Monumento',
    museum: 'Museo',
    performing_arts_theater: 'Teatro',
    sculpture: 'Escultura',
    amusement_center: 'Centro de ocio',
    amusement_park: 'Parque de atracciones',
    aquarium: 'Acuario',
    banquet_hall: 'Salón de eventos',
    botanical_garden: 'Jardín botánico',
    bowling_alley: 'Bolera',
    casino: 'Casino',
    comedy_club: 'Club de comedia',
    community_center: 'Centro comunitario',
    concert_hall: 'Sala de conciertos',
    convention_center: 'Centro de convenciones',
    cultural_center: 'Centro cultural',
    dance_hall: 'Sala de baile',
    dog_park: 'Parque canino',
    event_venue: 'Espacio para eventos',
    garden: 'Jardín',
    hiking_area: 'Zona de senderismo',
    internet_cafe: 'Cibercafé',
    karaoke: 'Karaoke',
    marina: 'Puerto deportivo',
    movie_theater: 'Cine',
    national_park: 'Parque nacional',
    night_club: 'Discoteca',
    observation_deck: 'Mirador',
    park: 'Parque',
    plaza: 'Plaza',
    tourist_attraction: 'Atracción turística',
    visitor_center: 'Centro de visitantes',
    water_park: 'Parque acuático',
    wedding_venue: 'Lugar de bodas',
    wildlife_park: 'Parque de fauna',
    zoo: 'Zoo',

    // Shopping and services
    accounting: 'Gestoría',
    atm: 'Cajero',
    bank: 'Banco',
    beauty_salon: 'Salón de belleza',
    book_store: 'Librería',
    car_dealer: 'Concesionario',
    car_rental: 'Alquiler de coches',
    car_repair: 'Taller mecánico',
    car_wash: 'Lavado de coches',
    clothing_store: 'Tienda de ropa',
    convenience_store: 'Tienda de conveniencia',
    corporate_office: 'Oficina',
    dentist: 'Dentista',
    doctor: 'Médico',
    drugstore: 'Droguería',
    electric_vehicle_charging_station: 'Punto de carga',
    electronics_store: 'Electrónica',
    florist: 'Floristería',
    furniture_store: 'Muebles',
    gas_station: 'Gasolinera',
    grocery_store: 'Supermercado',
    gym: 'Gimnasio',
    hair_care: 'Peluquería',
    hardware_store: 'Ferretería',
    home_goods_store: 'Hogar',
    hospital: 'Hospital',
    insurance_agency: 'Seguros',
    jewelry_store: 'Joyería',
    laundry: 'Lavandería',
    lawyer: 'Abogado',
    lodging: 'Alojamiento',
    pharmacy: 'Farmacia',
    real_estate_agency: 'Inmobiliaria',
    shopping_mall: 'Centro comercial',
    spa: 'Spa',
    store: 'Tienda',
    supermarket: 'Supermercado',
    veterinary_care: 'Veterinario',

    // Education, transport, public places
    airport: 'Aeropuerto',
    bus_station: 'Estación de autobús',
    bus_stop: 'Parada de autobús',
    church: 'Iglesia',
    city_hall: 'Ayuntamiento',
    courthouse: 'Juzgado',
    embassy: 'Embajada',
    fire_station: 'Bomberos',
    library: 'Biblioteca',
    light_rail_station: 'Estación de tren ligero',
    local_government_office: 'Oficina pública',
    mosque: 'Mezquita',
    parking: 'Aparcamiento',
    place_of_worship: 'Lugar de culto',
    police: 'Policía',
    post_office: 'Correos',
    preschool: 'Preescolar',
    primary_school: 'Colegio',
    school: 'Escuela',
    secondary_school: 'Instituto',
    stadium: 'Estadio',
    subway_station: 'Metro',
    synagogue: 'Sinagoga',
    taxi_stand: 'Parada de taxi',
    train_station: 'Estación de tren',
    transit_station: 'Transporte público',
    university: 'Universidad',

    // Generic response types
    establishment: 'Establecimiento',
    point_of_interest: 'Punto de interés',
    neighborhood: 'Barrio',
    locality: 'Localidad',
    political: 'Zona administrativa',
};

export function getPlaceTypeLabel(type: string): string {
    const normalized = type.trim();
    if (!normalized) return type;
    if (PLACE_TYPE_LABELS[normalized]) return PLACE_TYPE_LABELS[normalized];
    if (!normalized.includes('_')) return normalized;
    return normalized
        .split('_')
        .filter(Boolean)
        .map((part, index) => index === 0 ? part.charAt(0).toUpperCase() + part.slice(1) : part)
        .join(' ');
}

export function getPlaceTypeLabels(types?: string[], limit?: number): string[] {
    const values = Array.isArray(types) ? types : [];
    const selected = typeof limit === 'number' ? values.slice(0, limit) : values;
    return selected.map(getPlaceTypeLabel);
}
